version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true
    environment:
      discovery.type: single-node
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://localhost:9200

  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:7.3.0
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      - elasticsearch
    ports:
      - "8200:8200"